version: "3.9"
services:
  redis:
    restart: always
    volumes: 
      - ./docker/redis:/data
    image: ${IMAGE_NAME_REDIS}
  db:
    restart: always
    volumes: 
      - ./docker/db/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    image: ${IMAGE_NAME_POSTGRES}
  pg-admin:
    restart: always
    volumes: 
      - ./docker/pg-admin/servers.json:/pgadmin4/servers.json
      - ./docker/pg-admin/:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    image: ${IMAGE_NAME_PGADMIN}
  api:
    restart: always
    environment: 
      API_MODE: ${API_MODE}
      API_ADMIN_EMAIL: ${API_ADMIN_EMAIL}
      API_LISTEN_ADDR: ${API_LISTEN_ADDR}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_SESSION_KEY: ${AUTH_SESSION_KEY}
    depends_on:
      - db
      - redis
    image: ${IMAGE_NAME_API}
  notification:
    restart: always
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
    image: ${IMAGE_NAME_NOTIFICATION}
  nginx:
    restart: always
    volumes: 
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/html:/usr/share/nginx/html:ro
      - ./docker/nginx/cert:/root/cert:ro
    ports: 
      - 80:80
      - 443:443
    depends_on: 
      - api
      - pg-admin
    image: ${IMAGE_NAME_NGINX}