name: docker

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-api:${{ github.event.release.name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-api:latest
            ghcr.io/${{ github.repository_owner }}/backend-services-api:${{ github.event.release.name }}
            ghcr.io/${{ github.repository_owner }}/backend-services-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push loop
        id: docker_build_loop
        uses: docker/build-push-action@v2
        with:
          context: ./loop
          file: ./loop/Dockerfile
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-loop:${{ github.event.release.name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-loop:latest
            ghcr.io/${{ github.repository_owner }}/backend-services-loop:${{ github.event.release.name }}
            ghcr.io/${{ github.repository_owner }}/backend-services-loop:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache