name: CI to Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build api
        run: |
          cd api
          CGO_ENABLED=0 go build
          cd ..
      
      - name: Build notification
        run: |
          cd notification
          CGO_ENABLED=0 go build
          cd ..

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./api/Dockerfile
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-api:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-api:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push notification
        id: docker_build_notification
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./notification/Dockerfile
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-notification:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/backend-services-notification:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache